### ISSUE TITLE
Getting InvalidProjectFileException when running code generation on any Intent project using VSProjects and Nuget

### ISSUE THREAD

**Issue by dandrejvv** [IntentSoftware/Intent.Modules#130]
I am getting the following error when running the code generator:

```
ManifestLoader : Cant find assembly : Microsoft.Build.resources, Version=15.1.0.0, Culture=en-US, PublicKeyToken=b03f5f7f11d50a3a

Microsoft.Build.Exceptions.InvalidProjectFileException: Invalid static method invocation syntax: "[Microsoft.Build.Utilities.ToolLocationHelper]::GetPathToStandardLibraries($(TargetFrameworkIdentifier), $(TargetFrameworkVersion), $(TargetFrameworkProfile), $(PlatformTarget), $(TargetFrameworkRootPath), $(TargetFrameworkFallbackSearchPaths))". Method 'Microsoft.Build.Utilities.ToolLocationHelper.GetPathToStandardLibraries' not found. Static method invocation should be of the form: $([FullTypeName]::Method()), e.g. $([System.IO.Path]::Combine(`a`, `b`)).   C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Shared.ProjectErrorUtilities.VerifyThrowInvalidProject[T1,T2](Boolean condition, String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, T1 arg0, T2 arg1)
   at Microsoft.Build.Evaluation.Expander`2.Function`1.Execute(Object objectInstance, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation)
   at Microsoft.Build.Evaluation.Expander`2.PropertyExpander`1.ExpandPropertyBody(String propertyBody, Object propertyValue, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation, UsedUninitializedProperties usedUninitializedProperties)
   at Microsoft.Build.Evaluation.Expander`2.PropertyExpander`1.ExpandPropertiesLeaveTypedAndEscaped(String expression, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation, UsedUninitializedProperties usedUninitializedProperties)
   at Microsoft.Build.Evaluation.Expander`2.PropertyExpander`1.ExpandPropertiesLeaveEscaped(String expression, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation, UsedUninitializedProperties usedUninitializedProperties)
   at Microsoft.Build.Evaluation.Expander`2.ExpandIntoStringLeaveEscaped(String expression, ExpanderOptions options, IElementLocation elementLocation)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluatePropertyElement(ProjectPropertyElement propertyElement)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluatePropertyGroupElement(ProjectPropertyGroupElement propertyGroupElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(ILoggingService loggingService, BuildEventContext buildEventContext)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(IEvaluatorData`4 data, ProjectRootElement root, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCache projectRootElementCache, BuildEventContext buildEventContext, ProjectInstance projectInstanceIfAnyForDebuggerOnly, SdkResolution sdkResolution)
   at Microsoft.Build.Evaluation.Project.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings)
   at Intent.Modules.NuGet.Installer.NugetIntegration.CustomMsbuildProjectSystem.GetProject(String projectFile) in C:\Dev\Intent.Modules\Modules\Intent.Modules.NuGet.Installer\NugetIntegration\CustomMSBuildProjectSystem.cs:line 85
   at Intent.Modules.NuGet.Installer.ReImplementations.MSBuildProjectSystem..ctor(String msbuildDirectory, String projectFullPath, INuGetProjectContext projectContext, Boolean ignoreMissingImports) in C:\Dev\Intent.Modules\Modules\Intent.Modules.NuGet.Installer\ReImplementations\MSBuildProjectSystem.cs:line 34
   at Intent.Modules.NuGet.Installer.NugetIntegration.CustomMsbuildProjectSystem..ctor(String projectFullPath, INuGetProjectContext projectContext, Boolean ignoreMissingImports) in C:\Dev\Intent.Modules\Modules\Intent.Modules.NuGet.Installer\NugetIntegration\CustomMSBuildProjectSystem.cs:line 15
   at Intent.Modules.NuGet.Installer.NugetIntegration.NugetServices.GetProject(String project, ICanAddFileStrategy canAddFileStrategy) in C:\Dev\Intent.Modules\Modules\Intent.Modules.NuGet.Installer\NugetIntegration\NugetServices.cs:line 327
   at Intent.Modules.NuGet.Installer.NugetIntegration.NugetServices.GetInstalled(String project) in C:\Dev\Intent.Modules\Modules\Intent.Modules.NuGet.Installer\NugetIntegration\NugetServices.cs:line 269
   at Intent.Modules.NuGet.Installer.Managers.NugetManager.LoadMsbuildProject(String project) in C:\Dev\Intent.Modules\Modules\Intent.Modules.NuGet.Installer\Managers\NugetManager.cs:line 290
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at Intent.Modules.NuGet.Installer.Managers.NugetManager.LoadMsbuildProjects(String solutionFilePath, IEnumerable`1 additionalProjectFilePaths) in C:\Dev\Intent.Modules\Modules\Intent.Modules.NuGet.Installer\Managers\NugetManager.cs:line 266
   at Intent.Modules.NuGet.Installer.Managers.NugetManager..ctor(String solutionFilePath, ITracing tracing, NuGetManagerSettings settings, IEnumerable`1 projectFilePaths, IDictionary`2 canAddFileStrategies) in C:\Dev\Intent.Modules\Modules\Intent.Modules.NuGet.Installer\Managers\NugetManager.cs:line 53
   at Intent.Modules.NuGet.Installer.NugetInstaller.InstallForNetFramework(String solutionPath, IEnumerable`1 applicableProjects, ITracing tracing) in C:\Dev\Intent.Modules\Modules\Intent.Modules.NuGet.Installer\NugetInstaller.cs:line 100
   at Intent.Modules.NuGet.Installer.NugetInstaller.Run(IApplication application, ITracing tracing) in C:\Dev\Intent.Modules\Modules\Intent.Modules.NuGet.Installer\NugetInstaller.cs:line 80
   at Intent.Modules.NuGet.Installer.NugetInstaller.OnStep(IApplication application, String step) in C:\Dev\Intent.Modules\Modules\Intent.Modules.NuGet.Installer\NugetInstaller.cs:line 61
   at Intent.SoftwareFactory.ProcessOrchestration.<>c__DisplayClass19_0.<Process>b__11(IExecutionLifeCycle fe)
   at Intent.SoftwareFactory.FactoryExtensionHelper.ExtensionPoint[TImplements](String descritpion, Action`1 action)
   at Intent.SoftwareFactory.ProcessOrchestration.Process(String[] applicationIds)
   at Intent.SoftwareFactory.IntentManager.Run(String applicationIds)
   at Intent.SoftwareFactory.Factory.Run(ExecutionContext executionContext)
```

I ran the debugger and the code breaks on this line in `CustomMSBuildProjectSystem.cs`:

```c#
            var project = new Project(
                projectFile: projectFile,
                globalProperties: null,
                toolsVersion: null,
                projectCollection: ProjectCollection.GlobalProjectCollection,
                loadSettings: loadSettings);
```

I am not sure why this is happening, I even opened up other branches from source control to see if it wasn't any changes that I've introduced but it still persists. The only thing that I can think of is that Visual Studio 2017 got updated to the latest version today.

**Comment by dandrejvv** [comment]
Ok, I found the solution here:
https://stackoverflow.com/a/49511724/802755

Don't know how this happened but maybe the update messed around a bit but it is working now.

**Comment by JonathanLydall** [comment]
It must be Visual Studio update, I also started having the same issue and it has also coincided with my updating Visual Studio.

**Comment by dandrejvv** [comment]
@garethbaars is this definitely resolved now?
