### ISSUE TITLE
Could not validate license information when generating code

### ISSUE THREAD

**Issue by laredoza** [IntentSoftware/Intent.Modules#193]
Hi,

I hope this is the correct place to ask about the following:

I'm getting the following error when I try and generate code.

`Failed to set up execution environment:
System.Exception: Could not validate license information. ---> Microsoft.IdentityModel.Tokens.SecurityTokenInvalidLifetimeException: IDX10230: Lifetime validation failed. Delegate returned false, securitytoken: '[PII is hidden]'.
   at Microsoft.IdentityModel.Tokens.Validators.ValidateLifetime(Nullable`1 notBefore, Nullable`1 expires, SecurityToken securityToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateLifetime(Nullable`1 notBefore, Nullable`1 expires, JwtSecurityToken jwtToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateTokenPayload(JwtSecurityToken jwtToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Intent.SoftwareFactory.IntentExecutionEnvironment.DecodeAndValidateToken(String accessToken) in D:\AzureDevOpsAgents\IntentProprietaryRepository\_work\1\s\Intent.IntentArchitect\IntentArchitect.SoftwareFactory\Intent.SoftwareFactory\IntentExecutionEnvironment.cs:line 232
   --- End of inner exception stack trace ---
   at Intent.SoftwareFactory.IntentExecutionEnvironment.DecodeAndValidateToken(String accessToken) in D:\AzureDevOpsAgents\IntentProprietaryRepository\_work\1\s\Intent.IntentArchitect\IntentArchitect.SoftwareFactory\Intent.SoftwareFactory\IntentExecutionEnvironment.cs:line 265
   at Intent.SoftwareFactory.IntentExecutionEnvironment..ctor(ExecutionContext executionContext, IAssemblyLoadInterceptor[] assemblyLoadInterceptors) in D:\AzureDevOpsAgents\IntentProprietaryRepository\_work\1\s\Intent.IntentArchitect\IntentArchitect.SoftwareFactory\Intent.SoftwareFactory\IntentExecutionEnvironment.cs:line 65`

This error seems to come and go.

Enviroment:

Windows 10 & VS Studio Microsoft Visual Studio Community 2019 V 4.8.04084

**Comment by JonathanLydall** [comment]
Hi @laredoza,

Thanks for contacting us about this and sorry to see you're getting an error. From the stack trace it seems it's failing when trying to the validate that the token hasn't expired. The only way I can think of this happening is if your computer's clock and/or time zone time is incorrect, or Intent Architect can't talk to our server to automatically renew the token.

We'll improve the error message that can happen here, but can you perhaps confirm if your computer clock is correct to within a couple of minutes?

**Comment by laredoza** [comment]
Thanks, 

I think you're right, I experienced this on a dual boot system. It has Linux mint and Windows 10. If I log in on Windows 10 after having logged into Linux my time is 2 hours behind.
